[platformio]
default_envs = esp32
src_dir = src
boards_dir = boards

[env]
; --- Common for ALL ---
test_framework = googletest
upload_speed = 921600
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DLV_CONF_PATH="\"../hal/lv_conf.h\""
build_unflags =
    -std=c++11
    -std=gnu++11

[env:native]

test_filter = test_native
; --- Main PC Simulator ---
test_framework = googletest
platform = native
extends = env
build_src_filter = +<*> +<../lib> -<../lib/hal/LilyGo>
test_build_src = true
lib_deps =
    lvgl/lvgl @ 9.4.0
    bblanchon/ArduinoJson @ 7.2.1

build_flags =
    ${env.build_flags}
    -Ilib/test_common
    -Isrc
    -Ilib/gui
    -Ilib/hal
    -Ilib/native_replacements
    -DSDL_BUILD
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DLV_USE_SDL
    ; SDL paths from System Environment variables
    -I${sysenv.SDL2_INCLUDE_PATH}
    -L${sysenv.SDL2_LIBRARY_PATH}
    -lSDL2

[env:esp32]

test_filter = test_esp32
; --- Hardware Target ---
extends = env
monitor_filters =
    default
    esp32_exception_decoder
platform = espressif32@6.12.0
framework = arduino
board = T-Display-AMOLED
build_src_filter = +<*> +<../lib>
test_build_src = true
lib_deps =
    lvgl/lvgl @ 9.4.0
    bblanchon/ArduinoJson @ 7.2.1
    mikalhart/TinyGPSPlus @ 1.0.3
    adafruit/Adafruit NeoPixel @ 1.11.0
    bxparks/AceButton @ 1.10.1
    lewisxhe/XPowersLib @ 0.2.7
    lewisxhe/SensorLib @ 0.2.4
    bodmer/TFT_eSPI @ 2.5.0
    FS
    SPIFFS
    SD
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    paulstoffregen/OneWire @ 2.3.8
    WiFi
    HTTPClient

build_flags =
    ${env.build_flags}
    -Ilib/test_common
    -Isrc
    -Ilib/gui
    -Ilib/hal
    -DLILYGO_BUILD
    -DBOARD_HAS_PSRAM
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1

lib_ignore = native_replacements

[env:web]
platform = native
extends = env
build_src_filter = +<../lib/*> -<../lib/hal/LilyGo>
lib_deps =
    lvgl/lvgl @ 9.4.0
    bblanchon/ArduinoJson @ 7.2.1
extra_scripts =
  pre:extra_script.py

