#pragma once
// Include core types first
#include "./types/CalendarDate.hpp"
#include "./types/ChartSeries.hpp"
#include "./types/Color.hpp"
#include "./types/Enums.hpp"
#include "./types/StyleSelector.hpp"

// Include core classes
#include "./core/BaseWidget.hpp"
#include "./core/Component.hpp"
#include "./core/Screen.hpp"
#include "./core/Widget.hpp"

// Include the mixins
#include "./widgets/mixins/PartIndicatorProperties.hpp"
#include "./widgets/mixins/TextProperties.hpp"

// Include all widgets
#include "./widgets/AnimImage.hpp"
#include "./widgets/Arc.hpp"
#include "./widgets/Bar.hpp"
#include "./widgets/Button.hpp"
#include "./widgets/ButtonMatrix.hpp"
#include "./widgets/Calendar.hpp"
#include "./widgets/Canvas.hpp"
#include "./widgets/Chart.hpp"
#include "./widgets/Checkbox.hpp"
#include "./widgets/Dropdown.hpp"
#include "./widgets/Image.hpp"
#include "./widgets/ImageButton.hpp"
#include "./widgets/Keyboard.hpp"
#include "./widgets/Label.hpp"
#include "./widgets/Led.hpp"
#include "./widgets/Line.hpp"
#include "./widgets/List.hpp"
#include "./widgets/Menu.hpp"
#include "./widgets/MenuCont.hpp"
#include "./widgets/MenuPage.hpp"
#include "./widgets/MenuSection.hpp"
#include "./widgets/MessageBox.hpp"
#include "./widgets/Roller.hpp"
#include "./widgets/Scale.hpp"
#include "./widgets/Slider.hpp"
#include "./widgets/Spinbox.hpp"
#include "./widgets/Spinner.hpp"
#include "./widgets/Switch.hpp"
#include "./widgets/Tab.hpp"
#include "./widgets/Table.hpp"
#include "./widgets/Tabview.hpp"
#include "./widgets/TextArea.hpp"
#include "./widgets/Tile.hpp"
#include "./widgets/Tileview.hpp"
#include "./widgets/Window.hpp"
