/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main_wasm: (a: number) => void;
export const wasm_bridge_flush: (a: number, b: number, c: number) => void;
export const wasm_bridge_init: () => void;
export const wasm_bridge_read: (a: number, b: number) => void;
export const malloc: (a: number) => number;
export const free: (a: number) => void;
export const _start: () => void;
export const emscripten_stack_get_end: () => number;
export const emscripten_stack_get_base: () => number;
export const htonl: (a: number) => number;
export const htons: (a: number) => number;
export const ntohs: (a: number) => number;
export const setThrew: (a: number, b: number) => void;
export const _emscripten_tempret_set: (a: number) => void;
export const emscripten_stack_init: () => void;
export const emscripten_stack_get_free: () => number;
export const _emscripten_stack_restore: (a: number) => void;
export const _emscripten_stack_alloc: (a: number) => number;
export const emscripten_stack_get_current: () => number;
export const __cxa_decrement_exception_refcount: (a: number) => void;
export const __cxa_increment_exception_refcount: (a: number) => void;
export const __cxa_free_exception: (a: number) => void;
export const __get_exception_message: (a: number, b: number, c: number) => void;
export const __cxa_can_catch: (a: number, b: number, c: number) => number;
export const __cxa_get_exception_ptr: (a: number) => number;
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_start: () => void;
